version: "3.8"
services:
  backend:
    image: jasonkhew96/biliroaming-go-server
    restart: always
    env_file:
      - production.env
    secrets:
      - db-password
    environment:
      - PG_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 80:80

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
