version: "3.8"
services:
  backend:
    image: jasonkhew96/biliroaming-go-server
    restart: always
    env_file:
      - production.env
    secrets:
      - db-password
    environment:
      - PG_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 443
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - production.env
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432

  proxy:
    build: proxy
    ports:
      - 443:443
    depends_on:
      - backend

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
